# TCL File Generated by Component Editor 13.1
# Mon May 04 17:08:18 COT 2020
# DO NOT MODIFY


# 
# QUADRATURE_ENCODER_IP "QUADRATURE_ENCODER_IP" v1.0
# Andres-David Suarez-Gomez 2020.05.04.17:08:18
# It reads and counts the pulses of four quadrature encoders
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module QUADRATURE_ENCODER_IP
# 
set_module_property DESCRIPTION "It reads and counts the pulses of four quadrature encoders"
set_module_property NAME QUADRATURE_ENCODER_IP
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Mobile Robotics"
set_module_property AUTHOR "Andres-David Suarez-Gomez"
set_module_property DISPLAY_NAME QUADRATURE_ENCODER_IP
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL QUADRATURE_ENCODER_IP
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file D_FF.vhd VHDL PATH Hardware_Code/Custom_IP/QUADRATURE_ENCODER_IP/D_FF.vhd
add_fileset_file DIRECTION_RESET.vhd VHDL PATH Hardware_Code/Custom_IP/QUADRATURE_ENCODER_IP/DIRECTION_RESET.vhd
add_fileset_file JK_FF.vhd VHDL PATH Hardware_Code/Custom_IP/QUADRATURE_ENCODER_IP/JK_FF.vhd
add_fileset_file MULT_FREC_AND_ERROR_DETECT.vhd VHDL PATH Hardware_Code/Custom_IP/QUADRATURE_ENCODER_IP/MULT_FREC_AND_ERROR_DETECT.vhd
add_fileset_file OUTPUT_FORMING_CIRCUIT.vhd VHDL PATH Hardware_Code/Custom_IP/QUADRATURE_ENCODER_IP/OUTPUT_FORMING_CIRCUIT.vhd
add_fileset_file QUADRATURE_DEBOUNCE.vhd VHDL PATH Hardware_Code/Custom_IP/QUADRATURE_ENCODER_IP/QUADRATURE_DEBOUNCE.vhd
add_fileset_file QUADRATURE_DECODER.vhd VHDL PATH Hardware_Code/Custom_IP/QUADRATURE_ENCODER_IP/QUADRATURE_DECODER.vhd
add_fileset_file QUADRATURE_ENCODER_COUNTER.vhd VHDL PATH Hardware_Code/Custom_IP/QUADRATURE_ENCODER_IP/QUADRATURE_ENCODER_COUNTER.vhd
add_fileset_file QUADRATURE_ENCODER_IP.vhd VHDL PATH Hardware_Code/Custom_IP/QUADRATURE_ENCODER_IP/QUADRATURE_ENCODER_IP.vhd TOP_LEVEL_FILE
add_fileset_file TM.vhd VHDL PATH Hardware_Code/Custom_IP/QUADRATURE_ENCODER_IP/TM.vhd


# 
# parameters
# 
add_parameter CLK_FREQ NATURAL 50000000 ""
set_parameter_property CLK_FREQ DEFAULT_VALUE 50000000
set_parameter_property CLK_FREQ DISPLAY_NAME CLK_FREQ
set_parameter_property CLK_FREQ TYPE NATURAL
set_parameter_property CLK_FREQ UNITS None
set_parameter_property CLK_FREQ ALLOWED_RANGES 0:2147483647
set_parameter_property CLK_FREQ DESCRIPTION ""
set_parameter_property CLK_FREQ HDL_PARAMETER true
add_parameter TM_S NATURAL 100 ""
set_parameter_property TM_S DEFAULT_VALUE 100
set_parameter_property TM_S DISPLAY_NAME TM_S
set_parameter_property TM_S TYPE NATURAL
set_parameter_property TM_S UNITS None
set_parameter_property TM_S ALLOWED_RANGES 0:2147483647
set_parameter_property TM_S DESCRIPTION ""
set_parameter_property TM_S HDL_PARAMETER true
add_parameter RESET_ON_READ NATURAL 1
set_parameter_property RESET_ON_READ DEFAULT_VALUE 1
set_parameter_property RESET_ON_READ DISPLAY_NAME RESET_ON_READ
set_parameter_property RESET_ON_READ TYPE NATURAL
set_parameter_property RESET_ON_READ UNITS None
set_parameter_property RESET_ON_READ HDL_PARAMETER true
add_parameter N POSITIVE 8
set_parameter_property N DEFAULT_VALUE 8
set_parameter_property N DISPLAY_NAME N
set_parameter_property N TYPE POSITIVE
set_parameter_property N UNITS None
set_parameter_property N HDL_PARAMETER true
add_parameter DEBOUNCE_CYCLES POSITIVE 1
set_parameter_property DEBOUNCE_CYCLES DEFAULT_VALUE 1
set_parameter_property DEBOUNCE_CYCLES DISPLAY_NAME DEBOUNCE_CYCLES
set_parameter_property DEBOUNCE_CYCLES TYPE POSITIVE
set_parameter_property DEBOUNCE_CYCLES UNITS None
set_parameter_property DEBOUNCE_CYCLES HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 READDATA readdata Output 32
add_interface_port avalon_slave_0 READ_N read_n Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink CLOCK clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink RESETN reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end ENCODER_INPUT export Input 8


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender INT_SENDER irq Output 1

